apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: golang-http-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-http-dev
  template:
    metadata:
      labels:
        app: golang-http-dev
    spec:
      containers:
        - name: hello-gin
          image: gcr.io/k8s-0529/golang-http:latest
          ports:
            - containerPort: 8080
          env:
            - name: "PORT"
              value: "8080"